---
title: "Data Visualization Porject"
output: html_notebook
---

```{r}
library(tidyverse)

data <- read_csv("data/output.csv")
```

```{r}
summary(data)
```
```{r}
list(unique(data$emirate))
```
```{r}
head(data, 50)
```


```{r}
data$emirate <- factor(data$emirate)
data$class <- factor(data$class)
data$nationality <- factor(data$nationality)
```


```{r}
ggplot(data, aes(year, guests)) +
  geom_bar(stat="identity")
```


```{r}
data.sum <- data %>%
  group_by(year) %>%
  summarise(total_guests = sum(guests)) %>%
  arrange(year)

before <- subset(data.sum, year == 1985)$total_guests
after <- subset(data.sum, year == 2005)$total_guests

change <- ((after-before) / before)


before
after
change
```


```{r}
data.sum_5 <- data %>%
  filter(class == "Five star") %>%
  group_by(year) %>%
  summarise(total_guests = sum(guests)) %>%
  arrange(year)

before_5 <- subset(data.sum_5, year == 1985)$total_guests
after_5 <- subset(data.sum_5, year == 2005)$total_guests

change_5 <- ((after_5-before_5) / before_5)


before_5
after_5
change_5

after_5/after
```

```{r}
ggplot(data, aes(year, guests, fill=emirate)) +
  geom_bar(stat="identity")
```

```{r}
ggplot(data, aes(year, guests, fill=emirate)) +
  geom_bar(stat="identity") +
  facet_wrap(~nationality)
```

```{r}
ggplot(subset(data, emirate %in% c("Umm Al Quwain",
                                       "Ras Al-Khaimah and Fujairah",
                                       "Ajman and Sharjah")), 
       aes(year, guests, fill=emirate)) +
  geom_bar(stat="identity", position = "dodge")
```


```{r}
ggplot(data, aes(year, guests, fill=emirate)) +
  geom_bar(stat="identity") +
  facet_wrap(~nationality)
```

```{r}
ggplot(subset(data, emirate=="Abu Dhabi"), aes(year, guests, fill=class)) +
  geom_bar(stat="identity") +
  facet_wrap(~nationality)
```
```{r}
ggplot(subset(data, emirate=="Dubai" & 
                nationality == "UK"), aes(year, guests, fill=class)) +
  geom_bar(stat="identity") +
  facet_wrap(~nationality)
```

```{r}
ggplot(subset(data, emirate=="Dubai" & 
                nationality == "UK"), aes(year, nights, fill=class)) +
  geom_bar(stat="identity") +
  facet_wrap(~nationality)
```


```{r}
ggplot(subset(data, emirate=="Abu Dhabi" & 
                nationality == "UAE"), aes(year, guests, fill=class)) +
  geom_bar(stat="identity") +
  facet_wrap(~nationality)
```

```{r}
ggplot(subset(data, emirate == "Dubai" ), aes(year, guests, fill=class)) +
  geom_bar(stat="identity") +
  facet_wrap(~nationality)
```



```{r}
ggplot(subset(data, nationality %in% c("UK", "UAE", "Russia")),
       aes(year, guests, color=nationality)) +
  stat_summary(fun.y = mean, geom = "line") +
  stat_summary(fun.y = mean, geom = "point")
```

